package run.granite.gradle.generators

import java.io.File
import java.time.Instant

/**
 * Generates ReactNativeApplicationEntryPoint.java for SoLoader initialization
 * and New Architecture loading.
 *
 * This generator creates Java code that:
 * - Provides ReactNativeApplicationEntryPoint class with static loadReactNative method
 * - Initializes SoLoader with OpenSourceMergedSoMapping
 * - Conditionally loads New Architecture components
 * - Conditionally enables edge-to-edge UI
 * - Places generated code in com.facebook.react package
 * - Throws RuntimeException on SoLoader failure
 */
object EntryPointGenerator {
    /**
     * Generates ReactNativeApplicationEntryPoint.java file content.
     *
     * @param packageName The Android package name from project configuration
     * @return Generated Java code as string
     * @throws IllegalStateException if packageName is null
     */
    fun generate(packageName: String?): String {
        // Validate package name is present
        requireNotNull(packageName) {
            "Android package name not found in react-native config. " +
            "Ensure project has valid android configuration."
        }

        return buildString {
            appendLine("// Generated by Granite Gradle Plugin - DO NOT EDIT")
            appendLine("// This file is automatically generated during the build process")
            appendLine("// Generation timestamp: ${Instant.now()}")
            appendLine()
            appendLine("package com.facebook.react;")
            appendLine()
            appendLine("import android.content.Context;")
            appendLine("import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;")
            appendLine("import com.facebook.react.soloader.OpenSourceMergedSoMapping;")
            appendLine("import com.facebook.react.views.view.WindowUtilKt;")
            appendLine("import com.facebook.soloader.SoLoader;")
            appendLine()
            appendLine("/**")
            appendLine(" * ReactNativeApplicationEntryPoint provides static initialization for React Native runtime.")
            appendLine(" * This class handles SoLoader initialization and New Architecture component loading.")
            appendLine(" */")
            appendLine("public class ReactNativeApplicationEntryPoint {")
            appendLine()
            appendLine("  /**")
            appendLine("   * Loads the React Native runtime with proper SoLoader and New Architecture initialization.")
            appendLine("   *")
            appendLine("   * @param context Application context for SoLoader initialization")
            appendLine("   * @throws RuntimeException if SoLoader initialization fails")
            appendLine("   */")
            appendLine("  public static void loadReactNative(Context context) {")
            appendLine("    // Initialize SoLoader with merged shared object mapping")
            appendLine("    try {")
            appendLine("      SoLoader.init(context, OpenSourceMergedSoMapping.INSTANCE);")
            appendLine("    } catch (Exception e) {")
            appendLine("      throw new RuntimeException(\"Failed to initialize SoLoader\", e);")
            appendLine("    }")
            appendLine()
            appendLine("    // Load New Architecture components if enabled")
            appendLine("    // if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {")
            appendLine("    DefaultNewArchitectureEntryPoint.load();")
            appendLine("    WindowUtilKt.setEdgeToEdgeFeatureFlagOn();")
            appendLine("    // }")
            appendLine()
            appendLine("    // Enable edge-to-edge UI if configured")
            appendLine("    // if (BuildConfig.IS_EDGE_TO_EDGE_ENABLED) {")
            appendLine("      // Edge-to-edge feature flag is set in BuildConfig")
            appendLine("    // }")
            appendLine("  }")
            appendLine()
            appendLine("  private ReactNativeApplicationEntryPoint() {")
            appendLine("    // Utility class - prevent instantiation")
            appendLine("  }")
            appendLine("}")
        }
    }

    /**
     * Writes ReactNativeApplicationEntryPoint.java to the specified output directory.
     *
     * @param packageName Android package name from project configuration
     * @param outputDir Output directory for Java source files
     * @throws IllegalStateException if packageName is null
     */
    fun generateToFile(packageName: String?, outputDir: File) {
        val content = generate(packageName)

        // Create package directory structure: com/facebook/react/
        val packageDir = File(outputDir, "src/main/java/com/facebook/react")
        packageDir.mkdirs()

        val outputFile = File(packageDir, "ReactNativeApplicationEntryPoint.java")
        outputFile.writeText(content)
    }
}
