import { StyleSheet } from "react-native";

export const storeStyles = StyleSheet.create({
  screen: {
    backgroundColor: "#F6F0E5",
  },
  header: {
    backgroundColor: "#203028",
  },
  headerTitle: {
    fontWeight: "700",
  },
  home: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
  },
  eyebrow: {
    color: "#B44C2E",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.6,
    lineHeight: 16,
  },
  display: {
    marginTop: 8,
    color: "#203028",
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 38,
  },
  intro: {
    marginTop: 12,
    color: "#6F746D",
    fontSize: 16,
    lineHeight: 24,
  },
  productPanel: {
    marginTop: 32,
    padding: 20,
    borderLeftWidth: 4,
    borderLeftColor: "#B44C2E",
    backgroundColor: "#FFFDF8",
  },
  productLabel: {
    color: "#6F746D",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    lineHeight: 16,
  },
  productName: {
    marginTop: 8,
    color: "#203028",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 30,
  },
  productDescription: {
    marginTop: 8,
    color: "#6F746D",
    fontSize: 16,
    lineHeight: 24,
  },
  productFooter: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  price: {
    color: "#203028",
    fontSize: 24,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  stock: {
    color: "#6F746D",
    fontSize: 14,
  },
  bagCount: {
    marginTop: 24,
    color: "#203028",
    fontSize: 16,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  primaryAction: {
    minHeight: 52,
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
    backgroundColor: "#B44C2E",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  primaryActionPressed: {
    backgroundColor: "#8F3822",
  },
  primaryActionText: {
    color: "#FFFDF8",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryAction: {
    minHeight: 52,
    marginTop: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#D9CCB9",
    borderRadius: 4,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  secondaryActionPressed: {
    backgroundColor: "#FFFDF8",
  },
  secondaryActionText: {
    color: "#203028",
    fontSize: 16,
    fontWeight: "700",
  },
  walletAction: {
    minHeight: 52,
    marginTop: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
    backgroundColor: "#203028",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  walletActionPressed: {
    backgroundColor: "#6F746D",
  },
  walletActionText: {
    color: "#FFFDF8",
    fontSize: 16,
    fontWeight: "700",
  },
  productPage: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  productPageTitle: {
    marginTop: 8,
    color: "#203028",
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 38,
  },
  specPanel: {
    marginTop: 32,
    padding: 20,
    backgroundColor: "#FFFDF8",
  },
  specLabel: {
    color: "#6F746D",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    lineHeight: 16,
  },
  specValue: {
    marginTop: 8,
    color: "#203028",
    fontSize: 16,
    lineHeight: 24,
  },
  divider: {
    height: 1,
    marginVertical: 20,
    backgroundColor: "#D9CCB9",
  },
});
