import { StyleSheet } from "react-native";

export const walletStyles = StyleSheet.create({
  screen: {
    backgroundColor: "#071A2C",
  },
  header: {
    backgroundColor: "#061422",
  },
  headerTitle: {
    fontWeight: "700",
  },
  home: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 24,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  serviceLabel: {
    color: "#2FC6D5",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1.4,
    lineHeight: 18,
  },
  welcome: {
    marginTop: 4,
    color: "#F4F8FC",
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  status: {
    borderWidth: 1,
    borderColor: "#1C4566",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusText: {
    color: "#2FC6D5",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  balancePanel: {
    marginTop: 32,
    borderRadius: 20,
    backgroundColor: "#0D2943",
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  balanceLabel: {
    color: "#9DB2C7",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1.2,
    lineHeight: 18,
  },
  balance: {
    marginTop: 8,
    color: "#F4F8FC",
    fontSize: 38,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
    lineHeight: 44,
  },
  account: {
    marginTop: 8,
    color: "#9DB2C7",
    fontSize: 15,
    lineHeight: 22,
  },
  activityRow: {
    marginTop: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  activityTitle: {
    color: "#F4F8FC",
    fontSize: 18,
    fontWeight: "700",
  },
  transferCount: {
    color: "#2FC6D5",
    fontSize: 15,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  transaction: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 16,
    backgroundColor: "#0D2943",
    padding: 16,
  },
  transactionMark: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#1C4566",
  },
  transactionCopy: {
    flex: 1,
    marginLeft: 12,
  },
  transactionName: {
    color: "#F4F8FC",
    fontSize: 16,
    fontWeight: "600",
  },
  transactionMeta: {
    marginTop: 4,
    color: "#9DB2C7",
    fontSize: 13,
    lineHeight: 18,
  },
  transactionAmount: {
    color: "#F4F8FC",
    fontSize: 16,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  primaryAction: {
    minHeight: 52,
    marginTop: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    backgroundColor: "#2FC6D5",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  primaryActionPressed: {
    backgroundColor: "#1A97A4",
  },
  primaryActionText: {
    color: "#061422",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryAction: {
    minHeight: 52,
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#1C4566",
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  secondaryActionPressed: {
    backgroundColor: "#0D2943",
  },
  secondaryActionText: {
    color: "#F4F8FC",
    fontSize: 16,
    fontWeight: "700",
  },
  transferPage: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 48,
  },
  transferTitle: {
    marginTop: 16,
    color: "#F4F8FC",
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  transferAmount: {
    marginTop: 8,
    color: "#2FC6D5",
    fontSize: 38,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
    lineHeight: 44,
  },
  transferPanel: {
    width: "100%",
    marginTop: 32,
    borderRadius: 20,
    backgroundColor: "#0D2943",
    padding: 20,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  detailLabel: {
    color: "#9DB2C7",
    fontSize: 15,
    lineHeight: 22,
  },
  detailValue: {
    color: "#F4F8FC",
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 22,
  },
  divider: {
    height: 1,
    marginVertical: 16,
    backgroundColor: "#1C4566",
  },
});
