// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _IndexRoute } from '../pages/';
import type { Route as _AboutRoute } from '../pages/about';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
