enableGlobalCache: false

logFilters:
  - level: discard
    pattern: react-native * with version 0.72.6

nodeLinker: pnp

packageExtensions:
  '@react-native-community/cli-debugger-ui@*':
    dependencies:
      '@babel/runtime': ^7
  '@react-native/virtualized-lists@*':
    peerDependencies:
      react: '*'
  eslint-plugin-import@*:
    peerDependencies:
      typescript: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'

plugins:
  - .yarn/plugins/plugin-licenses.js

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-4.9.1.cjs
