enableGlobalCache: false

catalogs:
  list:
    swc:
      "@swc/core": 1.13.3
      "@swc/helpers": 0.5.17
    rn0_80_2:
      react: 19.1.0
      "@types/react": 19.1.0
      react-native: 0.80.2
      "@react-native-async-storage/async-storage": 2.2.0
      "@react-native-community/blur": 4.4.1
      "@react-navigation/elements": 1.3.9
      "@react-navigation/native": 6.0.13
      "@react-navigation/native-stack": 6.9.0
      "@shopify/flash-list": 2.0.2
      "lottie-react-native": 7.3.1
      "react-native-fast-image": 8.6.3
      "react-native-gesture-handler": 2.28.0
      "react-native-pager-view": 6.9.1
      "react-native-safe-area-context": 5.6.0
      "react-native-screens": 4.13.1
      "react-native-svg": 15.12.1
      "react-native-video": 6.16.1
      "react-native-webview": 13.15.0
      "@babel/plugin-transform-flow-strip-types": 7.27.1
      "@react-native/babel-preset": 0.81.0
    rn0_81_0:
      react: 19.1.0
      "@types/react": 19.1.0
      react-native: 0.81.0
      "@react-native-async-storage/async-storage": 2.2.0
      "@react-native-community/blur": 4.4.1
      "@react-navigation/elements": 2.6.3
      "@react-navigation/native": 7.1.17
      "@react-navigation/native-stack": 7.3.25
      "@shopify/flash-list": 2.0.2
      "lottie-react-native": 7.3.1
      "react-native-fast-image": 8.6.3
      "react-native-gesture-handler": 2.28.0
      "react-native-pager-view": 6.9.1
      "react-native-safe-area-context": 5.6.0
      "react-native-screens": 4.13.1
      "react-native-svg": 15.12.1
      "react-native-video": 6.16.1
      "react-native-webview": 13.15.0
      "@babel/plugin-transform-flow-strip-types": 7.27.1
      "@react-native/babel-plugin-codegen": 0.81.0
      "@react-native/babel-preset": 0.81.0
logFilters:
  - level: discard
    pattern: react-native * with version 0.72.6

nodeLinker: pnp

packageExtensions:
  "@react-native/codegen@*":
    dependencies:
      "@babel/parser": ^7
      "@babel/core": ^7
  "@react-native-community/cli-debugger-ui@*":
    dependencies:
      "@babel/runtime": ^7
  "@react-native/virtualized-lists@*":
    peerDependencies:
      react: "*"
    dependencies:
      "@babel/runtime": ^7
  "@typescript-eslint/type-utils@^8":
    dependencies:
      "@typescript-eslint/types": ^8
  eslint-plugin-import@*:
    peerDependencies:
      typescript: "*"
  jest-config@*:
    dependencies:
      ts-node: "*"
  react-native-fast-image@*:
    dependencies:
      "@babel/runtime": ^7
  react-native-video@*:
    peerDependencies:
      react: "*"
      react-native: "*"
  react-native-safe-area-context@*:
    dependencies:
      "@jest/globals": "*"
  react-native-svg@*:
    dependencies:
      buffer: ^6
  react-native@*:
    dependencies:
      "@babel/runtime": ^7

plugins:
  - .yarn/plugins/plugin-licenses.js
  - checksum: 674108d38f7697bddb93d6cc6046a871f8ea096d17ec7789cbb9c9cab2e11aebf3a73e891badffb884da94c76425d3b85a2e15cc5f90ee021eba804efb155550
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-4.9.1.cjs
