catalogs:
  brick-module:
    'brick-module': 0.4.0
  react-native:
    '@babel/plugin-transform-flow-strip-types': 7.27.1
    '@react-native-async-storage/async-storage': 2.2.0
    '@react-native-community/blur': 4.4.1
    '@react-native/babel-plugin-codegen': 0.81.3
    '@react-native/babel-preset': 0.81.3
    '@react-navigation/elements': 2.6.3
    '@react-navigation/native': 7.1.17
    '@react-navigation/native-stack': 7.3.25
    '@shopify/flash-list': 2.0.2
    '@types/react': 19.1.0
    lottie-react-native: 7.3.1
    react: 19.1.0
    '@types/react-dom': 19.2.3
    react-native: 0.81.3
    react-native-fast-image: 8.6.3
    react-native-gesture-handler: 2.28.0
    react-native-pager-view: 8.0.0
    react-native-safe-area-context: 5.6.0
    react-native-screens: 4.13.1
    react-native-svg: 15.14.0
    react-native-video: 6.16.1
    react-native-webview: 13.15.0
  swc:
    '@swc/core': 1.5.24
    '@swc/helpers': 0.5.17

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: react-native * with version 0.72.6

nodeLinker: pnp

npmPublishRegistry: 'https://registry.npmjs.org'

npmRegistries:
  'https://registry.npmjs.org':
    npmAlwaysAuth: true

packageExtensions:
  '@react-native-community/cli-debugger-ui@*':
    dependencies:
      '@babel/runtime': ^7
  '@react-native/codegen@*':
    dependencies:
      '@babel/core': ^7
      '@babel/parser': ^7
  '@react-native/virtualized-lists@*':
    peerDependencies:
      react: '*'
  '@typescript-eslint/type-utils@^8':
    dependencies:
      '@typescript-eslint/types': ^8
  eslint-plugin-import@*:
    peerDependencies:
      typescript: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
  react-native-fast-image@*:
    dependencies:
      '@babel/runtime': ^7
  react-native-safe-area-context@*:
    dependencies:
      '@jest/globals': '*'
  react-native-svg@*:
    dependencies:
      buffer: ^6
  react-native-video@*:
    peerDependencies:
      react: '*'
      react-native: '*'

plugins:
  - .yarn/plugins/plugin-licenses.js

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-4.10.3.cjs
