catalogs:
  brick-module:
    brick-module: 0.5.0
  react-native:
    '@babel/plugin-transform-flow-strip-types': 7.27.1
    '@react-native-async-storage/async-storage': 2.2.0
    '@react-native-community/blur': 4.4.1
    '@react-native/babel-plugin-codegen': 0.84.0-rc.5
    '@react-native/babel-preset': 0.84.0-rc.5
    '@react-navigation/elements': 2.9.5
    '@react-navigation/native': 7.1.28
    '@react-navigation/native-stack': 7.12.0
    '@shopify/flash-list': 2.0.2
    '@types/react': 19.2.0
    '@types/react-dom': 19.2.3
    react: 19.2.3
    react-dom: 19.2.3
    react-native: 0.84.0-rc.5
    '@react-native/dev-middleware': 0.84.0-rc.5
    react-native-gesture-handler: 2.30.0
    react-native-pager-view: 7.0.2
    react-native-safe-area-context: 5.6.2
    react-native-screens: 4.23.0
    react-native-svg: 15.15.2
    react-native-webview: 13.16.0
  swc:
    '@swc/core': 1.15.8
    '@swc/helpers': 0.5.17
  tools:
    react-native-builder-bob: 0.40.17
    tsdown: 0.20.3
    typescript: 5.9.3
    '@types/node': 24.10.12

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: react-native * with version 0.72.6

nodeLinker: pnp

npmPublishRegistry: 'https://registry.npmjs.org'

npmRegistries:
  'https://registry.npmjs.org':
    npmAlwaysAuth: true

packageExtensions:
  '@react-native-community/cli-debugger-ui@*':
    dependencies:
      '@babel/runtime': ^7
  '@react-native/codegen@*':
    dependencies:
      '@babel/core': ^7
      '@babel/parser': ^7
  '@react-native/virtualized-lists@*':
    peerDependencies:
      react: '*'
  '@typescript-eslint/type-utils@^8':
    dependencies:
      '@typescript-eslint/types': ^8
  eslint-plugin-import@*:
    peerDependencies:
      typescript: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
  react-native-safe-area-context@*:
    dependencies:
      '@jest/globals': '*'
  react-native-svg@*:
    dependencies:
      buffer: ^6

plugins:
  - .yarn/plugins/plugin-licenses.js

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-4.12.0.cjs
