coverage:
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 30%

ignore:
  - '**/*.test-d.*'

component_management:
  individual_components:
    - component_id: create-granite-app
      name: 'create-granite-app'
      paths:
        - packages/create-granite-app/**
    - component_id: mpack
      name: '@granite-js/mpack'
      paths:
        - packages/mpack/**
    - component_id: native
      name: '@granite-js/native'
      paths:
        - packages/native/**
    - component_id: native
      name: '@granite-js/native'
      paths:
        - packages/native/**
    - component_id: plugin-env
      name: '@granite-js/plugin-env'
      paths:
        - packages/plugin-env/**
    - component_id: plugin-hermes
      name: '@granite-js/plugin-hermes'
      paths:
        - packages/plugin-hermes/**
    - component_id: plugin-router
      name: '@granite-js/plugin-router'
      paths:
        - packages/plugin-router/**
    - component_id: react-native
      name: '@granite-js/react-native'
      paths:
        - packages/react-native/**
    - component_id: style-utils
      name: '@granite-js/style-utils'
      paths:
        - packages/style-utils/**
    - component_id: style-utils
      name: '@granite-js/style-utils'
      paths:
        - packages/style-utils/**
