import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, describe, expect, it } from 'vitest';
import { generateEnvType } from './generateEnvType';

describe('generateEnvType', () => {
  const tempDirectories: string[] = [];

  afterEach(() => {
    for (const directory of tempDirectories.splice(0)) {
      fs.rmSync(directory, { force: true, recursive: true });
    }
  });

  it('generates env types with Granite Rollipop client type reference', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'granite-env-type-'));
    tempDirectories.push(root);
    fs.mkdirSync(path.join(root, 'src'));

    generateEnvType(root, {
      MY_ENV: 'value',
    });

    expect(fs.readFileSync(path.join(root, 'src/env.d.ts'), 'utf-8')).toMatchInlineSnapshot(`
      "/// <reference types="@granite-js/react-native/types" />

      // Auto generated by env plugin. DO NOT EDIT.
      type Env = {
        MY_ENV: string;
      };

      interface ImportMeta {
        readonly env: Env & {};
      }
      "
    `);
  });
});
