name: Setup Node & Yarn
description: Setup Node & Yarn

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
              
    - name: Setup Yarn
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
