name: Setup Node & Yarn
description: Setup Node & Yarn

runs:
  using: composite
  steps:
    - name: Install Mise
      uses: jdx/mise-action@v4
      with:
        install: true

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
