// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`.device-manager {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  align-items: stretch;
  justify-content: center;
  gap: 2em;
  height: 100%;
  min-height: 400px;
  padding: 16px;
  background-color: var(--color-background);
  font-size: 14px;
}

.device-manager > header {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1em;
  text-align: center;
}

.device-manager > header > h1 {
  margin: 0;
  font-size: 2em;
  color: var(--color-text-primary);
}

.device-manager > header > p {
  margin: 0;
  font-size: 1em;
  color: var(--color-text-primary);
}

.device-manager > main > section {
  display: flex;
  flex-flow: column wrap;
  align-content: center;
  gap: 8px;
  max-width: 200px;
  margin: 0 auto;
}

.device-manager > main > section > .item {
  display: flex;
  align-items: center;
  font-size: 1.25em;
}

.device-manager > main > section > .item > .icon {
  padding: 2px;
  margin-right: 6px;
  border-radius: 4px;
  background-color: var(--color-background-elevation-1);
}

.device-manager > footer {
  font-size: 1.5em;
  text-align: center;
  color: var(--color-text-secondary);
}

/*# sourceURL=deviceManager.css */
`);

export default styles;
