// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`.devtools-container {
  width: 100%;
  height: 100%;
}

.loading-view {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  align-items: stretch;
  justify-content: center;
  gap: 2em;
  background-color: var(--color-background);
  font-size: 14px;
  text-align: center;
  z-index: 9999;
}

.loading-view.hide {
  display: none;
}

.loading-view > h1 {
  margin: 0;
  font-size: 1.5em;
  color: var(--color-text-primary);
}

.loading-view > p {
  margin: 0;
  font-size: 1em;
  color: var(--color-text-secondary);
}

/*# sourceURL=reactNativeDevtoolsStandalone.css */
`);

export default styles;
