export const NEW_ROUTE_FILE_TEMPLATE = `import React from 'react';
import { Text, View } from 'react-native';
import { createRoute } from '@granite-js/react-native';

export const Route = createRoute('%%path%%', {
  validateParams: (params) => params,
  component: %%componentName%%,
});

function %%componentName%%() {
  return (
    <View>
      <Text>Hello %%componentName%%</Text>
    </View>
  );
}
`;

export const ROUTER_GEN_TEMPLATE = `/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
%%pageImports%%

declare module '@granite-js/react-native' {
  interface RegisterScreen {
%%pageRoutes%%
  }
}
`;

export const NEW_LAYOUT_FILE_TEMPLATE = `import React, { PropsWithChildren } from 'react';

export default function %%componentName%%Layout({ children }: PropsWithChildren) {
  return (
    <>
      {children}
    </>
  );
}
`;
