// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

package run.granite.brownfield

import com.google.gson.annotations.SerializedName

/**
 * GraniteBrownfieldModule module types for Brick framework
 * Provides type-safe data classes with automatic serialization
 */


