// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

package run.granite.brownfield

import com.brickmodule.BrickModuleBase

/**
 * Generated interface for GraniteBrownfieldModule module
 * Implement this interface to create a type-safe GraniteBrownfieldModule module
 */
interface GraniteBrownfieldModuleSpec : BrickModuleBase {
    companion object {
        const val MODULE_NAME = "GraniteBrownfieldModule"
    }


    // MARK: - Module Constants

    val schemeUri: String


    // MARK: - Module Methods

    suspend fun closeView(): Unit


    // Override getConstants to provide module constants
    override fun getConstants(): Map<String, Any> = mapOf(
        "schemeUri" to schemeUri
    )
}


// Typed Event Emit Helpers for GraniteBrownfieldModule
/**
 * Emit visibilityChanged event to JavaScript
 * @param payload Event payload data
 */
fun GraniteBrownfieldModuleSpec.emitOnVisibilityChanged(payload: Map<String, Any>) {
    if (this is com.brickmodule.BrickModuleSpec) {
        this.emitEvent("onVisibilityChanged", payload)
    }
}
