// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

import Foundation
import BrickModule

/**
 * Generated protocol for Cookies module
 * Implement this protocol to create a type-safe Cookies module
 */
public protocol CookiesSpec {

    // MARK: - Module Methods

    /**
     * Set a cookie for a given URL
     * @param url - The URL to associate the cookie with
     * @param cookie - The cookie object to set
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to true on success
     */
    /// set method
    func set(url: String, cookie: CookiesCookie, useWebKit: Bool) async throws -> Bool

    /**
     * Get cookies for a given URL
     * @param url - The URL to get cookies for
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to a dictionary of cookies
     */
    /// get method
    func get(url: String, useWebKit: Bool) async throws -> [String: Any]

    /**
     * Get all cookies (iOS only, Android returns empty object)
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to a dictionary of all cookies
     */
    /// getAll method
    func getAll(useWebKit: Bool) async throws -> [String: Any]

    /**
     * Clear all cookies
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to true on success
     */
    /// clearAll method
    func clearAll(useWebKit: Bool) async throws -> Bool

    /**
     * Clear a specific cookie by name (iOS only)
     * @param url - The URL domain to clear the cookie from
     * @param name - The name of the cookie to clear
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to true on success
     */
    /// clearByName method
    func clearByName(url: String, name: String, useWebKit: Bool) async throws -> Bool

    /**
     * Set cookies from a Set-Cookie response header
     * @param url - The URL the response came from
     * @param cookie - The Set-Cookie header string
     * @returns Promise resolving to true on success
     */
    /// setFromResponse method
    func setFromResponse(url: String, cookie: String) async throws -> Bool

    /**
     * Get cookies that would be sent with a request to the URL
     * Returns them in Set-Cookie header format
     * @param url - The URL to get cookies for
     * @returns Promise resolving to the cookies as a header string
     */
    /// getFromResponse method
    func getFromResponse(url: String) async throws -> [String: Any]

    /**
     * Flush cookies to persistent storage (Android only)
     * On iOS, this is a no-op that resolves immediately
     * @returns Promise resolving when flush is complete
     */
    /// flush method
    func flush() async throws -> Bool

    /**
     * Remove session cookies (Android only)
     * On iOS, this is a no-op that resolves immediately
     * @returns Promise resolving to true on success
     */
    /// removeSessionCookies method
    func removeSessionCookies() async throws -> Bool
}
