// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

import Foundation
/// Cookies module types for Brick framework

public struct CookiesCookie: Codable {
    /// Cookie name (required)
    public let name: String
    /// Cookie value (required)
    public let value: String
    /// Cookie path (optional, defaults to "/")
    public let path: String?
    /// Cookie domain (optional)
    public let domain: String?
    /// Cookie version (optional)
    public let version: String?
    /// Expiration date as ISO string or timestamp (optional)
    public let expires: String?
    /// Whether cookie requires HTTPS (optional)
    public let secure: Bool?
    /// Whether cookie is HTTP-only (optional)
    public let httpOnly: Bool?

    public init(name: String, value: String, path: String?, domain: String?, version: String?, expires: String?, secure: Bool?, httpOnly: Bool?) {
        self.name = name
        self.value = value
        self.path = path
        self.domain = domain
        self.version = version
        self.expires = expires
        self.secure = secure
        self.httpOnly = httpOnly
    }
}
