export const preCompatibilityRemoteBundle = [
  'global._graniteMicroFrontend = global._graniteMicroFrontend || {',
  '  containers: {},',
  '  sharedModules: {},',
  '};',
  'function createContainer(appName, config) {',
  '  const containers = global._graniteMicroFrontend.containers;',
  '  if (containers[appName] != null) {',
  "    throw new Error(`App container '${appName}' is already registered`);",
  '  }',
  '  const container = { appName, config, exposedModules: {} };',
  '  containers[appName] = container;',
  '  return container;',
  '}',
  'function exposeModule(container, exposedModule, moduleValue) {',
  "  const normalizedModule = exposedModule.startsWith('./') ? exposedModule : `./${exposedModule}`;",
  '  if (container.exposedModules[normalizedModule] != null) {',
  "    throw new Error(`Exposed module '${normalizedModule}' is already registered in app container '${container.appName}'`);",
  '  }',
  '  container.exposedModules[normalizedModule] = moduleValue;',
  '}',
  'function registerShared(moduleName, moduleValue) {',
  '  const sharedModules = global._graniteMicroFrontend.sharedModules;',
  '  const existingModule = sharedModules[moduleName];',
  '  if (existingModule != null) {',
  '    if (Object.is(existingModule.get(), moduleValue)) {',
  '      return;',
  '    }',
  "    throw new Error(`Shared module '${moduleName}' is already registered`);",
  '  }',
  '  sharedModules[moduleName] = { get: () => moduleValue, loaded: true };',
  '}',
].join('\n');
