// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * Copyright 2021 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.rn-welcome-panel {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  align-items: stretch;
  justify-content: center;
  padding: 36px;
  background-color: var(--color-background-elevation-0);
  min-height: 100%;
}

@media (min-width: 1000px) {
  .rn-welcome-panel {
    flex-direction: row;
    align-items: center;
    justify-content: stretch;
    height: 100%;
    padding: 0;
  }
}

.rn-welcome-hero {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  flex-shrink: 0;
  align-items: center;
  justify-content: center;
  padding: 16px;
  text-align: center;
}

@media (min-width: 1000px) {
  .rn-welcome-hero {
    margin-left: 24px;
  }
}

.rn-welcome-heading {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
}

.rn-welcome-icon {
  width: 30px;
  height: 30px;
  border-radius: 4px;
  margin-right: 12px;
}

.rn-welcome-title {
  font-size: 20px;
  font-weight: normal;
  color: var(--color-text-primary);
}

.rn-welcome-title-accessory {
  margin-left: 12px;
  padding: 4px 8px;
  border-radius: 4px;
  background-color: var(--color-green);
  font-size: 12px;
  color: var(--color-on-primary);
}

.rn-welcome-title-accessory-purple {
  background-color: var(--color-purple-bright);
}

.rn-welcome-tagline {
  margin-bottom: 24px;
  font-size: 1rem;
  line-height: 1.3;
  color: var(--color-text-secondary);
}

.rn-welcome-links {
  display: flex;
  align-items: center;
}

.rn-welcome-links > .devtools-link {
  position: relative;
  margin: 0 16px;
  font-size: 14px;
}

.rn-welcome-links > .devtools-link:not(:last-child)::after {
  content: "";
  position: absolute;
  right: -16px;
  height: 16px;
  border-right: 1px solid var(--color-details-hairline);
}

.rn-welcome-version {
  position: fixed;
  top: 8px;
  right: 8px;
  margin-top: 24px;
  padding: 4px 12px;
  border-radius: 6px;
  background-color: var(--color-background-hover-overlay);
  color: var(--color-text-secondary);
  font-size: 11px;
}

.rn-welcome-docsfeed {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  align-items: stretch;
  max-width: 700px;
  margin: 0 auto;
  padding: 24px;
}

@media (min-width: 1000px) {
  .rn-welcome-docsfeed {
    flex-shrink: 1;
    width: 45%;
    max-height: 100%;
    margin: 0;
    padding: 20px 24px;
    padding-right: 80px;
    overflow: auto;
  }
}

.rn-welcome-h2 {
  flex-shrink: 0;
  font-size: 16px;
  font-weight: normal;
  color: var(--color-text-primary);
}

.rn-welcome-docsfeed-item {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  margin-bottom: 8px;
  padding: 8px;
  padding-right: 16px;
  border: 1px solid var(--color-details-hairline);
  border-radius: 4px;
  background-color: var(--color-background);
  text-align: left;
  font-size: 14px;
  cursor: pointer;
}

.rn-welcome-docsfeed-item:hover {
  background-color: var(--color-background-elevation-0);
}

.rn-welcome-docsfeed-item:focus {
  outline: solid var(--color-button-outline-focus);
}

.rn-welcome-docsfeed-item p {
  margin: 0;
  margin-bottom: 4px;
  text-decoration: none;
}

.rn-welcome-docsfeed-item :not(.devtools-link) {
  color: var(--color-text-secondary);
}

.rn-welcome-image {
  flex-shrink: 0;
  aspect-ratio: calc(16 / 9);
  height: 64px;
  margin-right: 16px;
  border-radius: 2px;
  background-color: var(--color-gray-100);
  background-position: center;
  background-size: cover;
}

/* Granite styles */
.granite-rn-welcome {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  align-items: stretch;
  justify-content: center;
  gap: 2em;
  height: 100%;
  min-height: 400px;
  padding: 16px;
  background-color: var(--color-background);
}

.granite-rn-welcome > header {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1em;
  text-align: center;
}

.granite-rn-welcome > header > img.granite-logo {
  width: 100px;
  height: 100px;
  object-fit: contain;
}

.granite-rn-welcome > header > h1 {
  margin: 0;
  font-size: 1.5em;
  color: var(--color-text-primary);
}

.granite-rn-welcome > header > p {
  margin: 0;
  font-size: 1em;
  color: var(--color-text-primary);
}

.granite-rn-welcome > main {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1em;
  margin: 1em 0;
}

.granite-rn-welcome > main > section.guide {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
  gap: 0.75em;
  font-size: 1em;
}

.granite-rn-welcome > main > section.guide > .item {
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 0.5em;
}

.granite-rn-welcome > footer {
  font-size: 1em;
  text-align: center;
  color: var(--color-text-secondary);
}

/*# sourceURL=rnWelcome.css */
`);

export default styles;
