// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright (c) 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.widget {
  padding: 20px;
}

.remote-debugging-terminated-title {
  font-size: 17px;
  font-weight: normal;
  margin: 6px 0;
}

.remote-debugging-terminated-message {
  font-size: 14px;
  margin: 5px 0;
  margin-bottom: 24px;
}

.remote-debugging-terminated-options {
  display: grid;
  grid-template-columns: 1fr auto;
  grid-gap: 8px;
  align-items: center;
  padding-top: 12px;
  border-top: 1px solid var(--color-details-hairline-light);
}

.remote-debugging-terminated-label {
  grid-column: 1;
  margin: 8px 0;
  max-width: 300px;
  font-size: larger;
  line-height: 1.4;
}

.remote-debugging-terminated-options .text-button {
  grid-column: 2;
}

.remote-debugging-terminated-feedback-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 16px;
  padding: 12px 16px;
  background-color: var(--color-background-elevation-1);
  border-radius: 6px;
}

.remote-debugging-terminated-feedback-label {
  font-size: 14px;
  margin-bottom: 8px;
}

.remote-debugging-terminated-reason {
  --override-reason-color: #8b0000;

  color: var(--override-reason-color);
}

.-theme-with-dark-background .remote-debugging-terminated-reason,
:host-context(.-theme-with-dark-background) .reason {
  --override-reason-color: rgb(255 116 116);
}

/*# sourceURL=remoteDebuggingTerminatedScreen.css */
`);

export default styles;
