// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

import Foundation
import BrickModule

/**
 * Generated protocol for GraniteBrownfieldModule module
 * Implement this protocol to create a type-safe GraniteBrownfieldModule module
 */
public protocol GraniteBrownfieldModuleSpec {
    // MARK: - Module Constants
    
    /// schemeUri constant
    var schemeUri: String { get }


    // MARK: - Module Methods

    /// closeView method
    func closeView() async throws
}

// Typed Event Emit Helpers for GraniteBrownfieldModule
extension GraniteBrownfieldModuleSpec where Self: BrickModuleBase {
    public func emitOnVisibilityChanged(payload: [String: Any]) {
        emit("onVisibilityChanged", payload: payload)
    }
}
