// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

package com.granitecookies

import com.google.gson.annotations.SerializedName

/**
 * Cookies module types for Brick framework
 * Provides type-safe data classes with automatic serialization
 */

/**
 * Cookie object representing a single HTTP cookie
 */
data class Cookie(
    /**
     * Cookie name (required)
     */
    @SerializedName("name")
    val name: String,
    /**
     * Cookie value (required)
     */
    @SerializedName("value")
    val value: String,
    /**
     * Cookie path (optional, defaults to "/")
     */
    @SerializedName("path")
    val path: String?,
    /**
     * Cookie domain (optional)
     */
    @SerializedName("domain")
    val domain: String?,
    /**
     * Cookie version (optional)
     */
    @SerializedName("version")
    val version: String?,
    /**
     * Expiration date as ISO string or timestamp (optional)
     */
    @SerializedName("expires")
    val expires: String?,
    /**
     * Whether cookie requires HTTPS (optional)
     */
    @SerializedName("secure")
    val secure: Boolean?,
    /**
     * Whether cookie is HTTP-only (optional)
     */
    @SerializedName("httpOnly")
    val httpOnly: Boolean?
)
