// This file is automatically generated by brick-codegen
// Do not edit manually - regenerate using: brick-codegen

package com.granitecookies

import com.brickmodule.BrickModuleBase
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap

/**
 * Generated interface for Cookies module
 * Implement this interface to create a type-safe Cookies module
 */
interface CookiesSpec : BrickModuleBase {
    companion object {
        const val MODULE_NAME = "Cookies"
    }


    // MARK: - Module Methods

    /**
     * Set a cookie for a given URL
     * @param url - The URL to associate the cookie with
     * @param cookie - The cookie object to set
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to true on success
     */
    suspend fun set(url: String, cookie: Cookie, useWebKit: Boolean): Boolean
    /**
     * Get cookies for a given URL
     * @param url - The URL to get cookies for
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to a dictionary of cookies
     */
    suspend fun get(url: String, useWebKit: Boolean): WritableMap
    /**
     * Get all cookies (iOS only, Android returns empty object)
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to a dictionary of all cookies
     */
    suspend fun getAll(useWebKit: Boolean): WritableMap
    /**
     * Clear all cookies
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to true on success
     */
    suspend fun clearAll(useWebKit: Boolean): Boolean
    /**
     * Clear a specific cookie by name (iOS only)
     * @param url - The URL domain to clear the cookie from
     * @param name - The name of the cookie to clear
     * @param useWebKit - Whether to use WebKit cookie store (iOS only)
     * @returns Promise resolving to true on success
     */
    suspend fun clearByName(url: String, name: String, useWebKit: Boolean): Boolean
    /**
     * Set cookies from a Set-Cookie response header
     * @param url - The URL the response came from
     * @param cookie - The Set-Cookie header string
     * @returns Promise resolving to true on success
     */
    suspend fun setFromResponse(url: String, cookie: String): Boolean
    /**
     * Get cookies that would be sent with a request to the URL
     * Returns them in Set-Cookie header format
     * @param url - The URL to get cookies for
     * @returns Promise resolving to the cookies as a header string
     */
    suspend fun getFromResponse(url: String): WritableMap
    /**
     * Flush cookies to persistent storage (Android only)
     * On iOS, this is a no-op that resolves immediately
     * @returns Promise resolving when flush is complete
     */
    suspend fun flush(): Boolean
    /**
     * Remove session cookies (Android only)
     * On iOS, this is a no-op that resolves immediately
     * @returns Promise resolving to true on success
     */
    suspend fun removeSessionCookies(): Boolean

}
