name: Release

on:
  push:
    branches:
      - main

env:
  BASE_BRANCH: 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-node-yarn

      - name: Update npm
        run: npm install -g npm@11.5.1

      - name: Run Build with Nx
        run: |
          yarn build:all

      - name: Create PR or Publish
        id: release
        uses: changesets/action@v1
        with:
          title: |
            chore: version packages ${{ env.BASE_BRANCH }}
          commit: 'chore: version packages'
          version: yarn changeset version
          publish: yarn workspaces foreach --all --no-private exec yarn npm publish --access public
        env:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
