/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _IndexRoute } from '../pages/';
import { Route as _ShowcaseImageRoute } from '../pages/showcase/image';
import { Route as _ShowcaseRoute } from '../pages/showcase';
import { Route as _ShowcaseInitialPropsRoute } from '../pages/showcase/initial-props';
import { Route as _ShowcaseLottieRoute } from '../pages/showcase/lottie';
import { Route as _ShowcaseSearchParamsRoute } from '../pages/showcase/search-params';
import { Route as _ShowcaseStatusBarRoute } from '../pages/showcase/status-bar';
import { Route as _ShowcaseUseBackEventRoute } from '../pages/showcase/use-back-event';
import { Route as _ShowcaseVideoRoute } from '../pages/showcase/video';
import { Route as _ShowcaseWebviewRoute } from '../pages/showcase/webview';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/showcase/image': (typeof _ShowcaseImageRoute)['_inputType'];
    '/showcase': (typeof _ShowcaseRoute)['_inputType'];
    '/showcase/initial-props': (typeof _ShowcaseInitialPropsRoute)['_inputType'];
    '/showcase/lottie': (typeof _ShowcaseLottieRoute)['_inputType'];
    '/showcase/search-params': (typeof _ShowcaseSearchParamsRoute)['_inputType'];
    '/showcase/status-bar': (typeof _ShowcaseStatusBarRoute)['_inputType'];
    '/showcase/use-back-event': (typeof _ShowcaseUseBackEventRoute)['_inputType'];
    '/showcase/video': (typeof _ShowcaseVideoRoute)['_inputType'];
    '/showcase/webview': (typeof _ShowcaseWebviewRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/showcase/image': (typeof _ShowcaseImageRoute)['_outputType'];
    '/showcase': (typeof _ShowcaseRoute)['_outputType'];
    '/showcase/initial-props': (typeof _ShowcaseInitialPropsRoute)['_outputType'];
    '/showcase/lottie': (typeof _ShowcaseLottieRoute)['_outputType'];
    '/showcase/search-params': (typeof _ShowcaseSearchParamsRoute)['_outputType'];
    '/showcase/status-bar': (typeof _ShowcaseStatusBarRoute)['_outputType'];
    '/showcase/use-back-event': (typeof _ShowcaseUseBackEventRoute)['_outputType'];
    '/showcase/video': (typeof _ShowcaseVideoRoute)['_outputType'];
    '/showcase/webview': (typeof _ShowcaseWebviewRoute)['_outputType'];
  }
}
