/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _IndexRoute } from '../pages/';
import { Route as _ShowcaseRoute } from '../pages/showcase';
import { Route as _ShowcaseLottieRoute } from '../pages/showcase/lottie';
import { Route as _ShowcaseVideoRoute } from '../pages/showcase/video';
import { Route as _ShowcaseWebviewRoute } from '../pages/showcase/webview';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/about': ReturnType<typeof _AboutRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/showcase': ReturnType<typeof _ShowcaseRoute.useParams>;
    '/showcase/lottie': ReturnType<typeof _ShowcaseLottieRoute.useParams>;
    '/showcase/video': ReturnType<typeof _ShowcaseVideoRoute.useParams>;
    '/showcase/webview': ReturnType<typeof _ShowcaseWebviewRoute.useParams>;
  }
}
